version: '3'

services:
  sub-web:
    build:
      context: .
      dockerfile: docker/sub-web.Dockerfile
    ports:
      - "80:80"
    depends_on:
      - subconverter
    restart: always

  subconverter:
    image: tindy2013/subconverter:latest
    ports:
      - "25500:25500"
    volumes:
      - ./config:/base/config
    restart: always 